package amiibo

import (
	"time"

	"golang.org/x/text/language"
)

// Amiibo is a generic interface for a Nintendo Amiibo product.
//
// Amiibo provides a handler to get all common fields between the ENGAmiibo and JPNAmiibo.
type Amiibo interface {

	// GetAvailable returns the Nintendo Amiibo product availability status.
	//
	// GetAvailable is calculated by evaluating the Nintendo Amiibo products release date is
	// before the current timestamp.
	GetAvailable() bool

	// GetID returns the Nintendo Amiibo products hash key ID.
	GetID() string

	// GetLanguage returns the Nintendo Amiibo products language identifier.
	GetLanguage() language.Tag

	// GetMD5 returns the Nintendo Amiibo products encoded MD5 hash sequence as well as the generated bytes.
	//
	// GetMD5 returns an additional error if the byte sequence cannot be generated or if the
	// MD5 hash cannot be produced.
	GetMD5() (string, []byte, error)

	// GetName returns the Nintendo Amiibo product name.
	//
	// GetName can contain unicode.
	GetName() string

	// GetNameAlternative returns the Nintendo Amiibo products alternative name.
	//
	// GetNameAlternative can contain unicode.
	GetNameAlternative() string

	// GetPrice returns the Nintendo Amiibo products retail price.
	//
	// GetPrice can contain unicode.
	GetPrice() string

	// GetReleaseDate returns the Nintendo Amiibo products retail release date as a formatted timestamp.
	GetReleaseDate() time.Time

	// GetSeries returns the series the Nintendo Amiibo product is affiliated with.
	//
	// GetSeries can contain unicode.
	GetSeries() string

	// GetURL return the direct URL to the Nintendo Amiibo product page.
	GetURL() string
}
