package amiibo

import (
	"time"

	"golang.org/x/text/language"
)

// Amiibo is a generic interface for a Nintendo Amiibo product.
//
// Amiibo provides a handler to get all common fields between the ENGAmiibo and JPNAmiibo.
type Amiibo interface {

	// GetAvailable returns the Amiibo's availability status.
	//
	// GetAvailable is calculated by evaluating the Amiibo's release date is
	// before the current timestamp.
	GetAvailable() bool

	// GetID returns the Amiibo's hash key ID.
	GetID() string

	// GetLanguage returns the Amiibo's language identifier.
	GetLanguage() language.Tag

	// GetMD5 returns the Amiibo's encoded MD5 hash sequence as well as the generated bytes.
	GetMD5() (string, []byte, error)

	// GetName returns the Amiibo's name.
	//
	// GetName can contain unicode.
	GetName() string

	// GetNameAlternative returns the Amiibo's alternative name.
	//
	// GetNameAlternative can contain unicode.
	GetNameAlternative() string

	// GetPrice returns the Amiibo's retail price.
	//
	// GetPrice can contain unicode.
	GetPrice() string

	// GetReleaseDate returns the Amiibo products retail release date as a formatted timestamp.
	GetReleaseDate() time.Time

	// GetSeries returns the series the Amiibo product is affiliated with.
	//
	// GetSeries can contain unicode.
	GetSeries() string
	GetURL() string
}
